AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instance and express server
Parameters:
  MyName:
    Type: String
    Default: Emma
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Resources:
  EmmaEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow incoming 22 and 80
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
  EmmaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref EmmaEC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo su
          cd ~
          yum update -y
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
          export NVM_DIR=\"$HOME/.nvm
          [ -s \"$NVM_DIR/nvm.sh\" ] && \. "$NVM_DIR/nvm.sh"
          [ -s \"$NVM_DIR/bash_completion\" ] && \. "$NVM_DIR/bash_completion\"
          . ~/.nvm/nvm.sh
          nvm install --lts
          yum install git -y
          git clone https://github.com/EmmaKingDev/expressToCloudFormation.git app
          cd app && npm install
          sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 3000
          npm start
      Tags:
        - Key: Owner
          Value: !Ref MyName
Outputs:
  EC2InstanceDNS:
    Value: !GetAtt EmmaEC2.PublicDnsName
